### ISSUE TITLE
Credential Error Uploading Experiment Data File

### ISSUE THREAD

**Issue by c-heat16** [C-Accel-CRIPT/Python-SDK#394]
**Describe the bug**
Trying to upload a data file as described in the [Scientist Python SDK Example Script](https://github.com/C-Accel-CRIPT/Python-SDK/discussions/373), and similar to as shown in the [simulation tutorial](https://c-accel-cript.github.io/Python-SDK/examples/simulation/#create-and-upload-files-nodes), throws a credential error, saying token has expired.

**To Reproduce**
To reproduce, run the script below. It works as intended if the file/data lines are commented out.
````
import os
import json
import cript

api_token = os.environ.get('CRIPT_API_TOKEN')
storage_token = os.environ.get('CRIPT_STORAGE_TOKEN')

api = cript.API(
    host='https://api.criptapp.org',
    api_token=api_token, storage_token=storage_token
)
api.connect()

SUFFIX = '10'

print('Creating project and collection...')
project = cript.Project(name='My Scratch Project {}'.format(SUFFIX))
collection = cript.Collection(name='My Scratch Collection {}'.format(SUFFIX))
project.collection += [collection]

print('Creating materials and inventory...')
pp = cript.Material(
    name='PP Scratch {}'.format(SUFFIX), identifier=[{'names': ['PP Scratch {}'.format(SUFFIX)]}]
)
product = cript.Material(
    name='Generic Product {}'.format(SUFFIX), identifier=[{'names': ['Generic Product {}'.format(SUFFIX)]}]
)

inventory_materials = [pp, product]

print('len(inventory_materials): {}'.format(len(inventory_materials)))
inventory = cript.Inventory(
    name='My Scratch Inventory {}'.format(SUFFIX),
    material=inventory_materials
)
collection.inventory += [inventory]

# EXPERIMENT 1
expt1 = cript.Experiment(
    'My Scratch Experiment {}-1'.format(SUFFIX),
)
collection.experiment += [expt1]

process1 = cript.Process(name='Pyrolysis 1', type='multistep', description='pyrolysis')
expt1.process += [process1]

pp_quantity1 = cript.Quantity(key='mass', value=1e-5, unit='kg')
initiator1 = cript.Ingredient(
    keyword=['initiator'], material=pp, quantity=[pp_quantity1]
)
process1.ingredient += [initiator1]

process1.product += [product]

yield_file = cript.File(
    name='Percent weight yield',
    type='data',
    source='/home/czh/nvme1/cript_sandbox/experiment_results/expt1/%WtYield_Chemicals.tsv'
)
yield_data = cript.Data(
    name='Percent weight yield',
    type='product_chemical_composition',
    file=[yield_file],
    notes='test',
)
expt1.data += [yield_data]

project.validate()
api.save(project)
````

Resulting error:
````
Traceback (most recent call last):
  File "/home/czh/nvme1/cript_sandbox/scratch.py", line 99, in <module>
    api.save(project)
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/cript/api/api.py", line 698, in save
    self._internal_save(project)
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/cript/api/api.py", line 722, in _internal_save
    file_node.ensure_uploaded(api=self)
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/cript/nodes/supporting_nodes/file.py", line 221, in ensure_uploaded
    self.source = _upload_file_and_get_object_name(source=self.source)
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/cript/nodes/supporting_nodes/file.py", line 73, in _upload_file_and_get_object_name
    object_name = api.upload_file(file_path=source)
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/cript/api/api.py", line 869, in upload_file
    self._s3_client.upload_file(Filename=file_path, Bucket=self._BUCKET_NAME, Key=object_name)  # type: ignore
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/cript/api/api.py", line 359, in _s3_client
    identity_id = auth.get_id(IdentityPoolId=self._IDENTITY_POOL_ID, Logins={self._COGNITO_LOGIN_PROVIDER: self._storage_token})
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/czh/nvme1/cript_sandbox/cript_venv/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotAuthorizedException: An error occurred (NotAuthorizedException) when calling the GetId operation: Invalid login token. Token expired: 1697547004 >= 1697459165
````

**Expected behavior**
The file is uploaded, attached to the data node, and associated with the experiment.

**Comment by nh916** [comment]
The issue you're encountering seems to be related to the AWS S3 tokens we use. These tokens, which can be obtained from the [frontend security page](https://app.criptapp.org/security/), have an expiration time for security purposes. The error suggests that the token you're using has expired. Please obtain a new token from the security page and try again. Let me know if you continue to face any issues!

**Comment by c-heat16** [comment]
Ah, gotcha, thanks for letting me know!
